name: test-new-pr
on: [pull_request, workflow_dispatch]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout ğŸ›ï¸Ivy Models
        uses: actions/checkout@v2
        with:
          path: models
          persist-credentials: false
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            "ivy_models_tests/**/*.py"

      - name: Run tests if any files in ivy_models_tests changed
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            docker run --rm -v `pwd`/models:/models unifyai/models:latest python3 -m pytest $file
          done
      